# Generated by Django 3.0.6 on 2020-07-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://image.freepik.com/free-vector/fast-food-vector-card-with-text-placeholder_78458-98.jpg', max_length=500),
        ),
    ]
